services:
  app:
    build:
      context: .
      dockerfile: docker/ktor/dev.Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
    volumes:
      - ./src:/home/gradle/app/src
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .dev.env
    networks:
      - skram-master-server-network
  db:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 1s
    env_file:
      - .dev.env
    ports:
      - "5432:5432"
    networks:
      - skram-master-server-network

  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    restart: always
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - skram-master-server-network
    env_file:
      - .dev.env

networks:
  skram-master-server-network: