ktor:
  application:
    modules:
      - com.skramMaster.infrastructure.ktorapp.ApplicationKt.module
  deployment:
    port: 8080
    postgres:
      - user: $POSTGRES_USER
      - password: $POSTGRES_PASSWORD
      - db: $POSTGRES_DB
    watch:
      - classes
      - resources
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
