ktor:
  application:
    modules:
      - com.skram_master.infrastructure.ktorapp.ApplicationKt.module
  deployment:
    port: 8080
    watch:
      - classes
      - resources
  development: $DEVELOPMENT_MODE
postgres:
  user: $DB_USER
  password: $DB_PASSWORD
  url: $DATABASE_URL
  test_user: $?TEST_DB_USER
  test_password: $?TEST_DB_PASSWORD
  test_url: $?TEST_DATABASE_URL
  migrations:
    directory: $MIGRATIONS_DIRECTORY
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
