ktor:
  application:
    modules:
      - com.skramMaster.infrastructure.ktorapp.ApplicationKt.module
  deployment:
    port: 8080
    watch:
      - classes
      - resources
postgres:
  name: $POSTGRES_DB
  user: $POSTGRES_USER
  password: $POSTGRES_PASSWORD
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
