ktor:
  application:
    modules:
      - com.skram_master.infrastructure.ktorapp.ApplicationKt.module
  deployment:
    port: 8080
    watch:
      - classes
      - resources
    development: $DEVELOPMENT_MODE
postgres:
  name: $DB_NAME
  user: $DB_USER
  password: $DB_PASSWORD
  url: $DATABASE_URL
  migrations:
    directory: $MIGRATIONS_DIRECTORY
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
