ktor:
  application:
    modules:
      - com.skramMaster.ApplicationKt.module
  deployment:
    port: 8080
    host: "0.0.0.0"
    watch:
      - classes
      - resources
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
