name: Setup Gradle

runs:
  using: "composite"
  steps:
    - name: Cache SDKMAN
      id: cache-sdkman-restore
      uses: actions/cache/restore@v4
      with:
        path: ~/.sdkman
        key: sdkman-java-22-amzn-${{ github.run_id }}
        restore-keys: sdkman-java-22-amzn-

    - name: Install SDKMAN and Corretto 22
      if: steps.cache-sdkman-restore.outputs.cache-matched-key == ''
      run: |
        curl -s "https://get.sdkman.io" | bash
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        sdk install java 22.0.2-amzn
      shell: bash

    - name: Set JAVA_HOME for Corretto 22
      run: |
        echo "JAVA_HOME=$HOME/.sdkman/candidates/java/current" >> $GITHUB_ENV
        echo "$HOME/.sdkman/candidates/java/current/bin" >> $GITHUB_PATH
      shell: bash

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Save SDKMAN Cache
      if: always() && steps.cache-sdkman-restore.outputs.cache-matched-key == ''
      uses: actions/cache/save@v4
      with:
        key: ${{ steps.cache-sdkman-restore.outputs.cache-primary-key }}
        path: ~/.sdkman
