name: detekt

on:
  push:
  pull_request:
    branches: [ "main", "develop", "feature/*" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 22 (Amazon Corretto)
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'amazon'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: detekt
        run: ./gradlew detekt