name: detekt

on:
  push:
  pull_request:
    branches: [ "main", "develop", "feature/*" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache SDKMAN
        uses: actions/cache@v3
        with:
          path: ~/.sdkman
          key: sdkman-java-22-amzn
          restore-keys: |
            sdkman-java-

      - name: Install SDKMAN and Corretto 22
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install java 22.0.2-amzn

      - name: Set JAVA_HOME for Corretto 22
        run: |
          echo "JAVA_HOME=$HOME/.sdkman/candidates/java/current" >> $GITHUB_ENV
          echo "$HOME/.sdkman/candidates/java/current/bin" >> $GITHUB_PATH

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: detekt
        run: ./gradlew detekt

      - name: Upload SARIF to GitHub using the upload-sarif action
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/detekt.sarif