name: detekt

on:
  # Comment out push for resource saving
  # push:
  pull_request:
    branches:
      - main
      - develop
      - 'feature/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/common/setup_gradle

      - name: detekt
        run: ./gradlew detekt -Pdetekt.autoCorrect=false --continue

      - name: Parse detekt report error
        if: failure()
        run: python .github/workflows/parse_detekt.py
        env:
          GITHUB_URL: ${{ github.server_url }}
          REPOSITORY_URL: ${{ github.repository }}
          BRANCH: ${{ github.head_ref }}
          DETEKT_REPORT_PATH: build/reports/detekt/merge.xml
