name: kotest

on:
  # Comment out push for resource saving
  # push:
  pull_request:
    branches:
      - main
      - develop
      - 'feature/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  kotest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/common/setup_gradle

      - name: clone Dto submodule
        env:
          DTO_TOKEN: ${{ secrets.SSH_PRIVATE_KEY_DTO }}
        run: |
          mkdir -p $HOME/.ssh/
          echo -e "$DTO_TOKEN" > $HOME/.ssh/id_rsa
          sudo chmod 600 $HOME/.ssh/id_rsa
          export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/id_rsa"
          git submodule update --init --force --recursive adapter/src/main/kotlin/com/skram_master/dto

      - name: clone Resource submodule
        env:
          RESOURCE_TOKEN: ${{ secrets.SSH_PRIVATE_KEY_RESOURCE }}
        run: |
          mkdir -p $HOME/.ssh/
          echo -e "$RESOURCE_TOKEN" > $HOME/.ssh/id_rsa
          sudo chmod 600 $HOME/.ssh/id_rsa
          export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/id_rsa"
          git submodule update --init --force --recursive infrastructure/ktorapp/src/main/kotlin/com/skram_master/resource

      - name: clone enum submodule
        env:
          ENUM_TOKEN: ${{ secrets.SSH_PRIVATE_KEY_ENUM }}
        run: |
          mkdir -p $HOME/.ssh/
          echo -e "ENUM_TOKEN" > $HOME/.ssh/id_rsa
          sudo chmod 600 $HOME/.ssh/id_rsa
          export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/id_rsa"
          git submodule update --init --force --recursive domain/src/main/kotlin/com/skram_master/enums

      - name: kotest
        run: |
          ./gradlew cleanTest --continue --parallel
          ./gradlew test -x detekt --continue --parallel